import type { Metadata } from 'next'
import { Gabarito as FontSans } from 'next/font/google'
import Script from 'next/script'

import '@repo/ui/globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Aglabs Bot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} bg-slate-50 font-sans antialiased`}
        suppressHydrationWarning
      >
        {children}
        {process.env.NODE_ENV === 'production' && (
          <Script
            async
            defer
            src="https://analytics.hendraaagil.dev/script.js"
            data-website-id="2513941b-6ff7-4a51-bb69-0126eeb4983e"
          />
        )}
      </body>
    </html>
  )
}
